# Generated by Django 4.1.3 on 2022-12-08 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 19, 45, 41, 643350), verbose_name='date published'),
        ),
    ]
