# Generated by Django 2.2.28 on 2022-12-12 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221211_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 20, 47, 7, 216951), verbose_name='date published'),
        ),
    ]
