# Generated by Django 2.2.28 on 2022-12-14 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221212_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 9, 6, 56, 994660), verbose_name='date published'),
        ),
    ]
